### ISSUE TITLE
User Story 5: Add Movies to Favorites List

### ISSUE THREAD

**Issue by Bilal4317** [Bilal4317/Capstone-Movie-Finder#12]
## Value Proposition

**As a** user
**I want to** be able to add movies to my favorites list  
**so that** I can easily access and keep track of movies I like.

​

## Description

The user can click on a "Add to Favorites" Heart icon for a movie in the list. The movie will be added to the user's favorites list.
​

## Acceptance Criteria

- [ ] Each movie in the list should have an "Add to Favorites"  icon.
- [ ] When the user clicks on the "Add to Favorites" icon, the movie should be added to the user's favorites list.
- [ ] The favorites list should be accessible and display the added movies.
      ​

## Tasks

- [ ] Implement an "Add to Favorites" functionality for each movie.
- [ ] Create a favorites list component.
- [ ] Store the added movies in the favorites list.
- [ ] Render the favorites list and display the added movies.

**Comment by Kheirah** [comment]
Where's the wireframe image? 🥲 
I like to visually see the things that need to be built.
