### ISSUE TITLE
user story 6 remove movie from favorites

### ISSUE THREAD

**Issue by Bilal4317** [Bilal4317/Capstone-Movie-Finder#14]
## Value Proposition

**As a** .user
**I want to** be able to remove movies from my favorites list
**so that*  I can manage my favorites more efficiently.
​

## Description

The user can click again on heart icon for a movie  The movie will be removed from the user's favorites list.
​

## Acceptance Criteria

- [ ] Each movie in the favorites list should have a heart icon .
- [ ] When the user clicks on the heart icon again , the movie should be removed from the user's favorites list.
- [ ] The favorites list should be updated immediately to reflect the removal of the movie.
      ​

## Tasks

- [ ]  Implement a "Remove from Favorites" functionality for each heart icon in the movie in the favorites list.
- [ ]   Update the favorites list state to remove the selected movie.
- [ ]  Render the updated favorites list after a movie is removed.

**Comment by Roland-Hufnagel** [comment]
LGTM
