### ISSUE TITLE
user profile

### ISSUE THREAD

**Issue by Bilal4317** [Bilal4317/Capstone-Movie-Finder#16]
## Value Proposition

**As a** user 
**I want to** have a personalized user profile 
**so that**  I can save and manage my movie preferences.
​

## Description
Create a user profile page where the user can log in or create an account to access personalized features. The user profile should allow the user to view and manage their favorites list 

​

## Acceptance Criteria

- [ ] The user should be able to create an account.
- [ ] and should be able to log in to access their personalized profile.
     ​

## Tasks

- [ ] create a user profile page.
- [ ] The users favorites should be stored in local storage
