### ISSUE TITLE
user story 8 : Dark mode

### ISSUE THREAD

**Issue by Bilal4317** [Bilal4317/Capstone-Movie-Finder#17]
## Value Proposition

**As a** User
**I want to** o have a dark mode option for the application
**so that**  I can customize the app's appearance according to my preferences.​

## Description

Implement a dark mode switch that allows users to switch between light and dark themes for the application.
​

## Acceptance Criteria

- [ ] * The dark mode switch should be visible and accessible to the user.
- [ ] * When the user toggles dark mode, the application's theme should change accordingly.

      ​

## Tasks

- [ ] Create a dark mode switch component.
- [ ] Implement functionality to toggle the dark mode theme for the application.
- [ ]  Store the users Theme preference using local storage.
