### ISSUE TITLE
Display movie search functionality user story 3

### ISSUE THREAD

**Issue by Bilal4317** [Bilal4317/Capstone-Movie-Finder#5]
## Value Proposition

**As a user 
**I want to search for movies,
**So that I can find specific movies I'm interested in.

## Description

The user can enter a search query in a search input field. The app will filter the movie data list based on the search query and display the matching movies.
​

## Acceptance Criteria

- [ ] The search input field should be visible and accessible to the user.
- [ ] When the user enters a search query, the movie data list should be filtered based on the query.
      ​

## Tasks

- [ ] Create a search input component.
- [ ]  Implement functionality to filter movie data based on the search query.
- [ ] Update the movie list to display only the matching movies.
- [ ]Handle cases where there are no matching movies.
- [ ] Handle cases where there are no matching movies.

**Comment by Miladu93** [comment]
good job!
