### ISSUE TITLE
View Movie Details on Click user story 2

### ISSUE THREAD

**Issue by Bilal4317** [Bilal4317/Capstone-Movie-Finder#6]
## Value Proposition

**As a** user 
**I want to** be able to click on a movie in the list to view its details
**so that** I can get more information about a specific movie.

## Description

.The user can click on a movie in the list to view its details, such as the title, description, and other information.

​

## Acceptance Criteria

- [ ] When the user clicks on a movie in the list, a separate page should open to display the movie details.
- [ ] The movie details should include the title, description, and other relevant information.

      ​

## Tasks

- [ ] Implement a click event handler for the movie component.
- [ ] Create a separate page to display the movie details.
- [ ] Pass the selected movie data to the  separate page for rendering.

**Comment by VolkerJacobsen** [comment]
Hi Bilal, wasn´t there supposed to be displayed an image of your app to showcase what you are about to do in this user story? If so, it is not showing.

**Comment by Miladu93** [comment]
looks great to me! good job bilal

**Comment by makitango** [comment]
Passing on that info works.
