### ISSUE TITLE
Sort Movie List based on Criteria user story 4

### ISSUE THREAD

**Issue by Bilal4317** [Bilal4317/Capstone-Movie-Finder#7]
## Value Proposition

**As a** User
**I want to** be able to sort the movie data list based on different criteria
**so that**  can customize the display of movies according to my preferences.​

## Description

The user can select a sorting option, such as by title, release date, or rating, to reorder the movie data list accordingly.

​

## Acceptance Criteria

- [ ] The sorting options should be visible and accessible to the user.
- [ ] When the user selects a sorting option, the movie data list should be reordered based on the selected criteria.
- [ ] The sorted movie list should be displayed immediately after the user selects a sorting option.
      ​

## Tasks

- [ ] Create navbar components.
- [ ] Implement a sorting mechanism for the movie data list based on the selected criteria.
- [ ] Render the sorted movie list after the user selects a sorting option.

**Comment by ekat-br** [comment]
Hi Bilal, what form are your sorting options in? As a button, dropdown menu, icons? Perhaps you could think about specifying this in more detail. Apart from that, good and clear user story.

**Comment by ekat-br** [comment]
LGTM💃
